name: 'Ludvig by Reothor'
description: 'Scan for secrets and vulnerabilities'
author: Frode Hus
branding:
  color: purple
  icon: eye
inputs:
  path: 
    description: 'Path to scan'
    required: true
    default: '.'
  customRulesPath:
    description: 'Path to custom YARA rules'
    required: false
  level:
    description: 'Only report findings above the given level [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL]'
    default: "MEDIUM"
    required: false
outputs:
  result: 
    description: 'Scan results'
runs:
  using: 'docker'
  image: 'docker://reothor/ludvig:0.2'
  args:
    - '-c ${{ inputs.customRulesPath }}'
    - '-p ${{ inputs.path }}'
    - '-l ${{ inputs.level }}'