name: 'Ludvig'
description: 'Scan for secrets and vulnerabilities'
inputs:
  path: 
    description: 'Path to scan'
    required: true
    default: '.'
outputs:
  result: 
    description: 'Scan results'
runs:
  using: 'docker'
  image: 'docker://reothor/ludvig:latest'
  args:
    - fs
    - ${{ inputs.path }}